image: clojure:lein

before_script: 
  - lein deps

coverage:
  stage: test
  script:
    - lein cloverage
  artifacts:
    paths:
      - target/coverage/

pages:
  stage: deploy
  dependencies:
    - coverage
  script:
    - mv target/coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master