image: clojure:lein

coverage:
  stage: test
  script:
    - lein deps
    - lein cloverage -o coverage
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - coverage
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master